//this works!!!!
g.V("B").addE('before').to(g.V('C'))
// don't touch it

g.addE(label).from(source).to(target)

uWgpU2jf0RNk-vDnaTsxdOHE4SkvmGx1ALsHSqkRanQ

g.addV('exercise').property('partitionKey','exercise').property('id','2316').property('movements', 'Dips')                  .property('Measured', "reps").property('Body part', 'Arms').property('Primary muscle',"Tricep").property('Derivative', 'Chest press').property('Equipment','03678').property('EquipMod1','0').property('EquipMod2','0').property('EquipMod3','04').property('Grip', '01236').property('GripMod', '02')
.addV('exercise').property('partitionKey','exercise').property('id','2317').property('movements', 'Shoulder Press')         .property('Measured', "reps").property('Body part', 'Arms').property('Primary muscle',"Shoulder").property('Derivative', 'Chest press').property('Equipment','012345678').property('EquipMod1','0').property('EquipMod2','0').property('EquipMod3','04').property('Grip', '01236').property('GripMod', '02')
.addV('exercise').property('partitionKey','exercise').property('id','2318').property('movements', 'Front Shoulder Raise')   .property('Measured', "reps").property('Body part', 'Arms').property('Primary muscle',"Shoulder").property('Derivative', 'Chest press').property('Equipment','03678').property('EquipMod1','0').property('EquipMod2','0').property('EquipMod3','04').property('Grip', '01236').property('GripMod', '02')
.addV('exercise').property('partitionKey','exercise').property('id','2319').property('movements', 'Side Shoulder Raise')    .property('Measured', "reps").property('Body part', 'Arms').property('Primary muscle',"Shoulder").property('Derivative', 'Chest press').property('Equipment','03678').property('EquipMod1','0').property('EquipMod2','0').property('EquipMod3','04').property('Grip', '01236').property('GripMod', '02')
    
//adding equipmentIDs
.V('1011').property('equipmentId','1')
.V('1012').property('equipmentId','2')
.V('1013').property('equipmentId','3')
.V('1014').property('equipmentId','4')
.V('1015').property('equipmentId','5')
.V('1016').property('equipmentId','6')
.V('1017').property('equipmentId','7')
.V('1018').property('equipmentId','8')
.V('1019').property('equipmentId','9')
.V('1020').property('equipmentId','1')
.V('1021').property('equipmentId','2')
.V('1022').property('equipmentId','3')
.V('1023').property('equipmentId','4')
.V('1024').property('equipmentId','5')
.V('1025').property('equipmentId','1')
.V('1026').property('equipmentId','2')
.V('1027').property('equipmentId','3')
.V('1028').property('equipmentId','4')
.V('1029').property('equipmentId','1')
.V('1030').property('equipmentId','2')
.V('1031').property('equipmentId','3')
.V('1032').property('equipmentId','4')
.V('1033').property('equipmentId','5')
.V('1034').property('equipmentId','6')
.V('1035').property('equipmentId','1')
.V('1036').property('equipmentId','2')
.V('1038').property('equipmentId','3')
.V('1038').property('equipmentId','1')
.V('1039').property('equipmentId','2')
.V('1040').property('equipmentId','3')
.V('1041').property('equipmentId','4')
.V('1042').property('equipmentId','5')
.V('1043').property('equipmentId','1')
.V('1044').property('equipmentId','2')
.V('1045').property('equipmentId','3')
.V('1046').property('equipmentId','4')
.V('1047').property('equipmentId','5')
.V('1048').property('equipmentId','6')
.V('1049').property('equipmentId','7')
.V('1050').property('equipmentId','8')
.V('1051').property('equipmentId','9')
.V('1052').property('equipmentId','a')
.V('1053').property('equipmentId','b')
.V('1054').property('equipmentId','c')
.V('1055').property('equipmentId','d')
.V('1056').property('equipmentId','e')
.V('1057').property('equipmentId','f')
.V('1058').property('equipmentId','g')
.V('1059').property('equipmentId','1')
.V('1060').property('equipmentId','2')
.V('1061').property('equipmentId','3')
.V('1062').property('equipmentId','4')
.V('1063').property('equipmentId','1')
.V('1064').property('equipmentId','2')
.V('1065').property('equipmentId','3')
.V('1066').property('equipmentId','4')
.V('1067').property('equipmentId','5')
.V('1068').property('equipmentId','6')
.V('1069').property('equipmentId','7')
.V('1070').property('equipmentId','8')
.V('1071').property('equipmentId','9')

